name: Publish Package to npmjs

on:
  workflow_dispatch:
    inputs:
      release_type:
        type: choice
        description: "<dev|latest>"
        required: true
        default: "dev"
        options:
          - dev
          - latest

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest
          registry-url: 'https://registry.npmjs.org/'

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: build
        run: |
          pnpm i --frozen-lockfile
          pnpm build:package
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: publish packages
        run: |
          pnpm --filter "./packages/*" publish --no-git-checks
